# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:

name: test-coverage.yaml

permissions: read-all

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Remove .Rprofile file (Unix)
        if: runner.os != 'Windows'
        run: |
          ls -la
          rm -r .Rprofile
          ls -la

      - name: Remove .Rprofile file (Windows)
        if: runner.os == 'Windows'
        run: |
          dir D:\a\SeedMaker\SeedMaker
          del .Rprofile
          dir D:\a\SeedMaker\SeedMaker

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.2'
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr, any::xml2
          needs: coverage

      - name: Test coverage
        run: covr::package_coverage()
        shell: Rscript {0}
